INSERT INTO guests (id, name, persona_description, expertise, tone, background, chemistry, domain, headshot_url, affiliation, created_at) VALUES 
('1d654271-8b21-4b1a-8c9a-7c98b23e1a01', 'Dr. Timnit Gebru', 'A fearless researcher challenging Big Tech hegemony and structural bias.', '["Algorithmic Bias", "Computer Vision", "Ethics"]', 'The Moral Compass.', 'Audience: Researchers. | Influence: Movement Leader.', '["The Moral Compass"]', '["Research"]', 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Timnit_Gebru_2022.jpg', 'DAIR Institute', 1762017826022),
('2e765382-9c32-5c2b-9d0b-8d09c34f2b12', 'Ali Alkhatib', 'Researcher mapping how automated systems shift power away from workers.', '["Labor Rights", "Gig Economy", "Surveillance"]', 'The Labor Advocate.', 'Audience: Workers. | Influence: Applied Ethicist.', '["The Labor Advocate"]', '["Labor & Tech"]', 'https://ali-alkhatib.com/assets/images/headshot.jpg', 'Center for Applied Data Ethics', 1762017826023),
('3f876493-0d43-6d3c-0e1c-9e10d45g3c23', 'Dr. Joy Buolamwini', 'The "Poet of Code" uncovering racial and gender bias in biometric tech.', '["Facial Recognition", "Biometrics", "Policy"]', 'The Inspired Visionary.', 'Audience: Public. | Influence: Legislative Catalyst.', '["The Inspired Visionary"]', '["Art & Science"]', 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Joy_Buolamwini.jpg', 'Algorithmic Justice League', 1762017826024),
('4a987504-1e54-7e4d-1f2d-0f21e56h4d34', 'Meredith Whittaker', 'Expert in the political economy of the AI industry and tech resistance.', '["Surveillance Capitalism", "Labor", "Monopoly"]', 'The Industry Insider.', 'Audience: Policy Makers. | Influence: Global Executive.', '["The Industry Insider"]', '["Industry"]', 'https://upload.wikimedia.org/wikipedia/commons/8/87/Meredith_Whittaker.jpg', 'Signal President', 1762017826025),
('5b098615-2f65-8f5e-2g3e-1g32f67i5e45', 'Dr. Safiya Noble', 'Scholar of how digital media and search engines reinforce racial inequality.', '["Search Bias", "Racial Equity", "Information Science"]', 'The Critical Scholar.', 'Audience: Students. | Influence: Theory Builder.', '["The Critical Scholar"]', '["Academic"]', 'https://safiyaunoble.com/wp-content/uploads/safiya-noble-headshot.jpg', 'UCLA Center for Critical Internet Inquiry', 1762017826026),
('6c109726-3g76-9g6f-3h4f-2h43g78j6f56', 'Dr. Ruha Benjamin', 'Exploring the "New Jim Code" where inequality is baked into automation.', '["Technological Racism", "Abolitionist AI", "Sociology"]', 'The Cultural Bridge.', 'Audience: Activists. | Influence: Narrative Shaper.', '["The Cultural Bridge"]', '["Sociology"]', 'https://ruhabenjamin.com/wp-content/uploads/ruha-benjamin.jpg', 'Princeton University', 1762017826027),
('7d210837-4h87-0h7g-4i5g-3i54h89k7g67', 'Sasha Costanza-Chock', 'Champion of tech for liberation through the lens of Design Justice.', '["Design Justice", "LGBTQ+ Equity", "Mutual Aid"]', 'The Radical Designer.', 'Audience: Designers. | Influence: Process Reformer.', '["The Radical Designer"]', '["Design"]', 'https://schock.cc/images/sasha-costanza-chock.jpg', 'Berkman Klein Center', 1762017826028),
('8e321948-5i98-1i8h-5j6h-4j65i90l8h78', 'Dr. Rumman Chowdhury', 'Pioneer in algorithmic red teaming and corporate tech accountability.', '["Governance", "Red Teaming", "Accountability"]', 'The Pragmatic Auditor.', 'Audience: CEOs. | Influence: Policy Advisor.', '["The Pragmatic Auditor"]', '["Business"]', 'https://humaneintelligence.org/wp-content/uploads/rumman-chowdhury.jpg', 'Humane Intelligence', 1762017826029),
('9f432059-6j09-2j9i-6k7i-5k76j01m9i89', 'Abeba Birhane', 'Critical scientist studying the impact of AI on the Global South.', '["Relational Ethics", "Global South", "Data Extraction"]', 'The Philosophical Voice.', 'Audience: Philosophers. | Influence: Ethical Provocateur.', '["The Philosophical Voice"]', '["Global South"]', 'https://abeba-birhane.github.io/images/abeba_birhane.jpg', 'Mozilla Fellow', 1762017826030),
('0a543160-7k10-3k0j-7l8j-6l87k12n0j90', 'Tawana Petty', 'Community-centered organizer fighting invasive surveillance tech.', '["Data Justice", "Grassroots", "Privacy"]', 'The Community Shield.', 'Audience: Local Organizers. | Influence: Defender of Privacy.', '["The Community Shield"]', '["Grassroots"]', 'https://pettypropolis.org/wp-content/uploads/tawana-petty-headshot.jpg', 'Algorithmic Justice League', 1762017826031);