-- D1 Migration: Seed data from legacy data.ts
-- Formats expertise, chemistry, and domain as valid JSON arrays to prevent UI parse errors

DELETE FROM episodes;
DELETE FROM research;
DELETE FROM guests;

-- EPISODES
INSERT INTO episodes (id, title, description, created_at) VALUES 
('0efd56dc-9c2b-424a-be8b-c50edb283914', 'The Algorithmic Class Divide', 'How redlining turned into algorithmic bias. Exploring the historical roots of discriminatory lending practices and their modern AI-powered manifestations in credit scoring and mortgage approval systems.', 1762017406475),
('1b2e1e74-8cd4-4da1-8a45-0001e9ba7cab', 'Investing in Liberation: AI as a Tool for Economic Justice', 'Can machine learning models be used to identify and fund underserved communities? A conversation about using AI to democratize access to capital.', 1762017406850),
('7d4d4ce7-6bce-431b-9059-5d4c786127bf', 'The Ghost in the Machine: Bias Audits for Financial AI', 'Deep dive into fairness testing frameworks, intersectional bias detection, and the regulatory landscape for AI in finance.', 1762017407250),
('8cdcc389-808a-4408-b3fa-d26c452f1cdb', 'Decolonizing Data: Who Owns the Training Sets?', 'Examining data extraction, consent, and ownership in AI systems used for credit and risk assessment in the Global South.', 1762017407553),
('d55804dd-ad35-4022-b69f-3dba16202e6e', 'From Payday Loans to Prediction Markets: AI and Financial Predation', 'How AI-powered fintech can either exploit or empower vulnerable populations. Case studies from predatory lending detection systems.', 1762017407867),
('f6682aab-64b8-4766-84c8-6c5122384ef6', 'The Builder and The Critic: This format moves beyond a simple debate to create a constructive dialogue between a leading AI founder and a premier critic of AI''s social impact', 'This format moves beyond a simple debate to create a constructive dialogue between a leading AI founder and a premier critic of AI''s social impact. The objective is to explore how deep critique can inform the foundational design philosophy of new technologies, moving ethics from a compliance checklist to a core product principle. Kanjun Qiu is building AI with the explicit goal of enhancing human agency and creativity. Ruha Benjamin''s work meticulously documents how current technological systems often disempower and harm marginalized communities, and she offers "abolitionist tools" for a more just approach. The guiding question for this conversation is not "Is AI good or bad?" but rather: How could Benjamin''s "abolitionist tools" be practically integrated into the architectural and ethical framework of an AI company like Imbue from its inception? This dialogue would transform a powerful critique into a potential design specification, offering a roadmap for a more equitable mode of AI development. Featuring Kanjun Qiu (CEO, Imbue) & + Ruha Benjamin (Author, Race After Technology).', 1762017835528),
('6d8ee9ca-7b33-4ed1-b059-ea5ad6d7a6c0', 'The Code and The Consequence: This pairing juxtaposes a technologist creating sophisticated, automated governance systems with a researcher who has documented the devastating real-world failures of similar systems', 'This pairing juxtaposes a technologist creating sophisticated, automated governance systems with a researcher who has documented the devastating real-world failures of similar systems. This grounds the promise of technical solutions in the lived experience of those most affected by their implementation. John Nay is building "Regulatory AI" to automate legal and regulatory compliance, aiming to create more efficient and auditable systems of governance. Virginia Eubanks'' research provides a harrowing account of how automated welfare and social service systems have created a "digital poorhouse," punishing the poor for minor errors and reinforcing systemic bias. The core tension to explore is: Can Nay''s sophisticated, law-as-code approach be a genuine solution to the bureaucratic injustices Eubanks identifies, or does it risk creating an even more efficient and inescapable "digital poorhouse"? This conversation would force a pragmatic visionary to confront the human consequences of automated decision-making at its most brutal. Featuring John Nay (Founder, Norm AI) & + Virginia Eubanks (Author, Automating Inequality).', 1762017836207),
('87a00f4e-f062-4658-9626-5c0325a24d29', 'The Capital and The Culture: This discussion brings together two leaders who deploy capital to shape culture and drive social change, but who operate at vastly different scales and with divergent risk profiles', 'This discussion brings together two leaders who deploy capital to shape culture and drive social change, but who operate at vastly different scales and with divergent risk profiles. The conversation would be a meta-analysis of the podcast''s own title, exploring the different strategies of ''Renegade Capital''. Darren Walker helms a multi-billion-dollar institution, working to steer its immense resources toward justice and equity from within the establishment. Christine Kuan leads a nimble organization founded specifically to fund the risk-taking, avant-garde artists that larger institutions might overlook. The guiding question is: What are the distinct and complementary roles of large-scale institutional philanthropy and agile, "renegade" funding in fostering a just and creatively vibrant society? Where do they overlap, and where must they necessarily diverge? This would be a masterclass in the strategy of social change through financial leverage. Featuring Darren Walker (President, Ford Foundation) & + Christine Kuan (President, Creative Capital).', 1762017836900),
('77bd3f2e-0f54-4bf8-9e6a-79531b18c649', 'The Future of Human Labor (Part 1): The Economist''s View', 'A three-episode series that examines the impact of AI on the future of work from three distinct and crucial perspectives: the macro-economist, the on-the-ground labor organizer, and the life-course strategist. The arc would begin with Daron Acemoglu, who can lay out the stark economic framework of automation''s "displacement effect" on labor and the societal danger of the "Turing Trap". Featuring Daron Acemoglu.', 1762017837553),
('2ed59538-7c76-4448-83ea-4827db13b65f', 'The Future of Human Labor (Part 2): The Worker''s View', 'A three-episode series that examines the impact of AI on the future of work from three distinct and crucial perspectives: the macro-economist, the on-the-ground labor organizer, and the life-course strategist. Featuring , Ai-jen Poo.', 1762017838182),
('6fbcb738-8861-43d3-8baa-44c9f8e57925', 'The Future of Human Labor (Part 3): The Life-Course View', 'A three-episode series that examines the impact of AI on the future of work from three distinct and crucial perspectives: the macro-economist, the on-the-ground labor organizer, and the life-course strategist. Featuring , and Lynda Gratton.', 1762017838483);

-- RESEARCH
INSERT INTO research (id, name, domain, chemistry, topic, link, date_added, created_at, headshot_url, affiliation) VALUES 
('1a69902b-7312-4828-9b9f-d4899f5d8117', 'Joy Buolamwini', 'AI Ethics', 'Visionary', 'Algorithmic Justice and Financial Equity', 'https://www.ajlunited.org', 1760486400, 1762017408196, NULL, NULL),
('25cafc25-5f19-440b-af38-a22d5f4f0082', 'Ruha Benjamin', 'Science & Technology Studies', 'Critical Thinker', 'Race After Technology: Abolitionist Tools for the New Jim Code', 'https://www.ruhabenjamin.com', 1760572800, 1762017408594, 'Hosted within press kit via https://www.ruhabenjamin.com/media', 'Princeton University'),
('94e5d92a-8e50-4e58-9f51-9c6b318dee86', 'Timnit Gebru', 'AI Research', 'Truth-Teller', 'Data Colonialism and AI Accountability', 'https://www.dair-institute.org', 1760745600, 1762017409033, NULL, NULL),
('b4732422-0084-4bb4-b666-105a9aff752a', 'Safiya Umoja Noble', 'Information Studies', 'Analytical', 'Algorithms of Oppression: How Search Engines Reinforce Racism', 'https://safiyaunoble.com', 1760918400, 1762017409502, 'https://gender.ucla.edu/wp-content/uploads/2019/04/S_Noble.jpg', 'UCLA Center on Race & Digital Justice'),
('77e00d50-d746-4e4a-83f0-a06aae7de50b', 'Cathy O''Neil', 'Data Science', 'Pragmatist', 'Weapons of Math Destruction: How Big Data Increases Inequality', 'https://mathbabe.org', 1761091200, 1762017409986, NULL, NULL);

-- GUESTS (Reformatting into strict JSON Arrays for UI compatibility)
INSERT INTO guests (id, name, persona_description, expertise, tone, background, chemistry, domain, headshot_url, affiliation, created_at) VALUES 
('53f62237-24a6-4249-8154-faad535c37de', 'Kate Crawford', 'The leading cross-disciplinary critic of AI''s planetary and political costs.', '["AI & Society", "Politics", "Environment"]', 'The Systems Thinker.', 'Audience: Academic. | Influence: Public Intellectual.', '["The Systems Thinker"]', '["Academic"]', 'https://images.squarespace-cdn.com/content/v1/655cb99992574744b5a625e4/f960adf2-174d-4c49-aa2c-abdb49983c2a/katephoto_cath_muscat_scaled.png', 'USC / Microsoft Research', 1762017826021),
('8c9f4801-d8ed-4b8a-9718-e36b4ee38022', 'Ruha Benjamin', 'Originator of the "New Jim Code" framework for understanding tech and racial bias.', '["Sociology", "African American Studies", "Science & Technology Studies"]', 'The Abolitionist Scholar.', 'Audience: Social Justice Advocates. | Influence: Public Intellectual.', '["The Abolitionist Scholar"]', '["Social Justice"]', 'Hosted within press kit via https://www.ruhabenjamin.com/media', 'Princeton University', 1762017826375),
('31888dd1-ace9-4d4a-8078-8fc52e7b0956', 'Safiya Umoja Noble', 'Foundational scholar on how search engines reinforce racism and sexism.', '["Information Studies", "Gender Studies", "Algorithmic Bias"]', 'The Digital Archivist.', 'Audience: General Intellectually Curious. | Influence: Public Intellectual.', '["The Digital Archivist"]', '["Information Studies"]', 'https://gender.ucla.edu/wp-content/uploads/2019/04/S_Noble.jpg', 'UCLA Center on Race & Digital Justice', 1762017826792),
('34eb3e88-47e5-4ac1-9396-769985e59783', 'Meredith Broussard', 'A practitioner-critic who makes complex algorithmic bias accessible and tangible.', '["Data Journalism", "AI Ethics", "Algorithmic Accountability"]', 'The Translator.', 'Audience: Journalists, Tech Professionals. | Influence: Industry Leader.', '["The Translator"]', '["Data Science"]', 'https://news.umflint.edu/2024/03/19/nyu-professor-meredith-broussard-to-discuss-bias-in-technology-march-27/', 'New York University / UM-Flint', 1762017827177),
('8a2dc201-5104-45a3-85e6-81f436c1c6be', 'Virginia Eubanks', 'Investigative storyteller documenting the "digital poorhouse" and its human cost.', '["Political Science", "Technology", "Poverty & Social Justice"]', 'The Investigative Storyteller.', 'Audience: Policy Makers, Activists. | Influence: Public Intellectual.', '["The Investigative Storyteller"]', '["Social Justice"]', NULL, NULL, 1762017827492),
('be5d1e99-afc4-46e4-87ce-9df60bf69c7b', 'Marzyeh Ghassemi', 'A leading builder of fair and robust AI systems for high-stakes healthcare applications.', '["AI in Healthcare", "Machine Learning", "Health Equity"]', 'The Rigorous Builder.', 'Audience: Tech Professionals, Healthcare Innovators. | Influence: Industry Leader.', '["The Rigorous Builder"]', '["Tech", "Healthcare"]', 'https://www.csail.mit.edu/sites/default/files/styles/headshot/public/images/people/profile/IMG_3006.jpeg?h=88c62e36&itok=hf_XXeeJ', 'MIT CSAIL / Jameel Clinic', 1762017827903),
('19890d52-075b-4fe8-a8aa-de1fa6567c9f', 'Nita Farahany', 'A legal futurist defining the coming battle for "cognitive liberty" and mental privacy.', '["Law", "Neuroscience", "AI Ethics", "Bioethics"]', 'The Legal Futurist.', 'Audience: Legal Professionals, Futurists. | Influence: Public Intellectual.', '["The Legal Futurist"]', '["Law", "Ethics"]', NULL, NULL, 1762017828236),
('346a40a8-938b-4a46-92d8-216b7dd2ca61', 'John Nay', 'Founder building market-based solutions to automate AI alignment using legal code.', '["AI & Law", "Regulatory Tech", "Entrepreneurship"]', 'The Pragmatic Visionary.', 'Audience: VCs, Fintech Professionals. | Influence: Industry Leader.', '["The Pragmatic Visionary"]', '["Tech", "Law"]', 'https://conferences.law.stanford.edu/futurelaw2024/wp-content/uploads/sites/166/2024/03/Nay_John.jpg', 'Norm AI / Stanford Law', 1762017828580),
('f7838094-2945-4d39-a4be-181abc53c3b2', 'Shannon Vallor', 'A leading voice on how AI is reshaping human virtue, character, and morality.', '["Philosophy of Technology", "AI Ethics", "Virtue Ethics"]', 'The Moral Philosopher.', 'Audience: Academics, Ethicists. | Influence: Public Intellectual.', '["The Moral Philosopher"]', '["Philosophy"]', 'https://www.audible.com/author/Shannon-Vallor/B01LY76PK2?srsltid=AfmBOoocI48wF1bsx948dGPYi1X872QEbQ2vxaU5yv8cuH7jAIkZoNSW', 'University of Edinburgh', 1762017828815),
('2c9b6505-b524-41b7-8cc7-8bcffe33d3a1', 'Daron Acemoglu', 'A top economist offering a critical, data-driven perspective on automation''s true impact on labor.', '["Economics", "Automation", "Labor Markets"]', 'The Skeptical Economist.', 'Audience: Economists, Policy Makers. | Influence: Public Intellectual.', '["The Skeptical Economist"]', '["Economics"]', 'https://en.wikipedia.org/wiki/Daron_Acemoglu', 'MIT / Nobel Committee', 1762017829100),
('e4674428-865a-4b61-84dd-8525b14cd969', 'Darren Walker', 'Leader of a major philanthropic institution deploying capital for social justice at scale.', '["Philanthropy", "Social Justice", "Finance"]', 'The Statesman.', 'Audience: Non-profit Leaders, Philanthropists. | Influence: Global Leader.', '["The Statesman"]', '["Philanthropy"]', 'https://gcp-na-images.contentstack.com/v3/assets/bltea6093859af6183b/blte54e0c028c224cdf/6998cd01e1ba0036a098e467/time-closers-2026-darren-walker-01.jpg?branch=production&width=3840&quality=75&auto=webp&crop=4:5', 'Ford Foundation', 1762017829465),
('252c739e-3002-40d5-bcff-6e0d6e3222f2', 'Ai-jen Poo', 'A MacArthur-winning organizer representing the workers most affected by the future of work.', '["Labor Activism", "Social Justice", "Future of Work"]', 'The Grassroots Organizer.', 'Audience: Activists, Labor Organizers. | Influence: Public Intellectual.', '["The Grassroots Organizer"]', '["Labor"]', 'https://upload.wikimedia.org/wikipedia/commons/4/41/Ai-jen_Poo%2C_National_Domestic_Workers_Alliance%2C_2015.jpg', 'National Domestic Workers Alliance', 1762017829756),
('b4e886e0-345b-4d92-aa51-10d4543c19c3', 'Lauren Maffeo', 'An on-the-ground practitioner implementing responsible AI policy in state government.', '["Civic Tech", "AI Governance", "Public Policy"]', 'The Civic Implementer.', 'Audience: Public Sector Employees, Civic Tech. | Influence: Niche Expert.', '["The Civic Implementer"]', '["Tech", "Policy"]', 'https://www.aspendigital.org/wp-content/uploads/2025/10/LM-CB-Headshot-Lauren-Maffeo-e1759960099604.webp', 'State of Maryland', 1762017830049),
('a4fb547a-ed06-4889-9f1e-a99d441c2012', 'Karen Hao', 'The definitive inside-chronicler of OpenAI and the global race for AI dominance.', '["Journalism", "AI", "China Tech"]', 'The Insider Chronicler.', 'Audience: Tech Insiders, VCs, Journalists. | Influence: Industry Leader.', '["The Insider Chronicler"]', '["Journalism"]', 'https://images.squarespace-cdn.com/content/v1/64a4ee85e22ab3529f73f53f/615dcd4d-93a7-47ad-9e65-23b3a8b3c9cf/KarenHao.jpg', 'Investigative Journalist / Author', 1762017830369),
('add71b23-706b-4336-b187-95cd93199658', 'Mo Wang', 'A researcher applying the science of human behavior to the future of work and aging.', '["Behavioral Economics", "Future of Work", "Occupational Psychology"]', 'The People Scientist.', 'Audience: HR Professionals, Business Leaders. | Influence: Niche Expert.', '["The People Scientist"]', '["Psychology"]', 'https://b768902a.delivery.rocketcdn.me/wp-content/uploads/profiles/mo-wang-5309-3x4.jpg', 'University of Florida', 1762017830678),
('8a67620f-9516-4b5c-bc5c-4e138ae28396', 'Christoph Nedopil Wang', 'An authority on the global financial flows shaping sustainable development and climate action.', '["Green Finance", "Sustainable Development", "Climate Tech"]', 'The Global Economist.', 'Audience: Climate Investors, Policy Makers. | Influence: Industry Leader.', '["The Global Economist"]', '["Economics", "Finance"]', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1i-uCVvcbxGbf3JFQYJwNjx7FhYmnqjtQvw&s', 'Green Finance & Development Center', 1762017830999);
