export const episodes = [
  {
    "id": "0efd56dc-9c2b-424a-be8b-c50edb283914",
    "title": "The Algorithmic Class Divide",
    "description": "How redlining turned into algorithmic bias. Exploring the historical roots of discriminatory lending practices and their modern AI-powered manifestations in credit scoring and mortgage approval systems.",
    "created_at": 1762017406475,
  },
  {
    "id": "1b2e1e74-8cd4-4da1-8a45-0001e9ba7cab",
    "title": "Investing in Liberation: AI as a Tool for Economic Justice",
    "description": "Can machine learning models be used to identify and fund underserved communities? A conversation about using AI to democratize access to capital.",
    "created_at": 1762017406850,
  },
  {
    "id": "7d4d4ce7-6bce-431b-9059-5d4c786127bf",
    "title": "The Ghost in the Machine: Bias Audits for Financial AI",
    "description": "Deep dive into fairness testing frameworks, intersectional bias detection, and the regulatory landscape for AI in finance.",
    "created_at": 1762017407250,
  },
  {
    "id": "8cdcc389-808a-4408-b3fa-d26c452f1cdb",
    "title": "Decolonizing Data: Who Owns the Training Sets?",
    "description": "Examining data extraction, consent, and ownership in AI systems used for credit and risk assessment in the Global South.",
    "created_at": 1762017407553,
  },
  {
    "id": "d55804dd-ad35-4022-b69f-3dba16202e6e",
    "title": "From Payday Loans to Prediction Markets: AI and Financial Predation",
    "description": "How AI-powered fintech can either exploit or empower vulnerable populations. Case studies from predatory lending detection systems.",
    "created_at": 1762017407867,
  },
  {
    "id": "09e76755-e359-4c5b-88ed-d602e55cad5f",
    "title": "The Algorithmic Class Divide",
    "description": "How redlining turned into algorithmic bias. Exploring the historical roots of discriminatory lending practices and their modern AI-powered manifestations in credit scoring and mortgage approval systems.",
    "created_at": 1762017585703,
  },
  {
    "id": "17f8a1c3-d252-44d7-985b-7744b9f14379",
    "title": "Investing in Liberation: AI as a Tool for Economic Justice",
    "description": "Can machine learning models be used to identify and fund underserved communities? A conversation about using AI to democratize access to capital.",
    "created_at": 1762017585899,
  },
  {
    "id": "73fd25fb-ba7e-46c0-811c-8b97f1d66440",
    "title": "The Ghost in the Machine: Bias Audits for Financial AI",
    "description": "Deep dive into fairness testing frameworks, intersectional bias detection, and the regulatory landscape for AI in finance.",
    "created_at": 1762017586232,
  },
  {
    "id": "c8829841-4c5a-474d-abd5-fb02c030efae",
    "title": "Decolonizing Data: Who Owns the Training Sets?",
    "description": "Examining data extraction, consent, and ownership in AI systems used for credit and risk assessment in the Global South.",
    "created_at": 1762017586541,
  },
  {
    "id": "ba46fffa-4cd5-43b4-882c-2c7bc40c3164",
    "title": "From Payday Loans to Prediction Markets: AI and Financial Predation",
    "description": "How AI-powered fintech can either exploit or empower vulnerable populations. Case studies from predatory lending detection systems.",
    "created_at": 1762017586910,
  },
  {
    "id": "93ebfe21-102b-4a5d-9d24-d1ffc4ab5949",
    "title": "The Algorithmic Class Divide",
    "description": "How redlining turned into algorithmic bias. Exploring the historical roots of discriminatory lending practices and their modern AI-powered manifestations in credit scoring and mortgage approval systems.",
    "created_at": 1762017721078,
  },
  {
    "id": "87f20496-e828-48d0-b902-0a7f6eba3e57",
    "title": "Investing in Liberation: AI as a Tool for Economic Justice",
    "description": "Can machine learning models be used to identify and fund underserved communities? A conversation about using AI to democratize access to capital.",
    "created_at": 1762017721500,
  },
  {
    "id": "eedd0465-33c1-4207-92cc-1045179e10e2",
    "title": "The Ghost in the Machine: Bias Audits for Financial AI",
    "description": "Deep dive into fairness testing frameworks, intersectional bias detection, and the regulatory landscape for AI in finance.",
    "created_at": 1762017721826,
  },
  {
    "id": "076b8051-3e0c-43f9-93e8-b099211d9a21",
    "title": "From Payday Loans to Prediction Markets: AI and Financial Predation",
    "description": "How AI-powered fintech can either exploit or empower vulnerable populations. Case studies from predatory lending detection systems.",
    "created_at": 1762017722433,
  },
  {
    "id": "f6682aab-64b8-4766-84c8-6c5122384ef6",
    "title": "The Builder and The Critic: This format moves beyond a simple debate to create a constructive dialogue between a leading AI founder and a premier critic of AI's social impact",
    "description": "This format moves beyond a simple debate to create a constructive dialogue between a leading AI founder and a premier critic of AI's social impact. The objective is to explore how deep critique can inform the foundational design philosophy of new technologies, moving ethics from a compliance checklist to a core product principle. Kanjun Qiu is building AI with the explicit goal of enhancing human agency and creativity. Ruha Benjamin's work meticulously documents how current technological systems often disempower and harm marginalized communities, and she offers \"abolitionist tools\" for a more just approach. The guiding question for this conversation is not \"Is AI good or bad?\" but rather: How could Benjamin's \"abolitionist tools\" be practically integrated into the architectural and ethical framework of an AI company like Imbue from its inception? This dialogue would transform a powerful critique into a potential design specification, offering a roadmap for a more equitable mode of AI development. Featuring Kanjun Qiu (CEO, Imbue) & + Ruha Benjamin (Author, Race After Technology).",
    "created_at": 1762017835528,
  },
  {
    "id": "6d8ee9ca-7b33-4ed1-b059-ea5ad6d7a6c0",
    "title": "The Code and The Consequence: This pairing juxtaposes a technologist creating sophisticated, automated governance systems with a researcher who has documented the devastating real-world failures of similar systems",
    "description": "This pairing juxtaposes a technologist creating sophisticated, automated governance systems with a researcher who has documented the devastating real-world failures of similar systems. This grounds the promise of technical solutions in the lived experience of those most affected by their implementation. John Nay is building \"Regulatory AI\" to automate legal and regulatory compliance, aiming to create more efficient and auditable systems of governance. Virginia Eubanks' research provides a harrowing account of how automated welfare and social service systems have created a \"digital poorhouse,\" punishing the poor for minor errors and reinforcing systemic bias. The core tension to explore is: Can Nay's sophisticated, law-as-code approach be a genuine solution to the bureaucratic injustices Eubanks identifies, or does it risk creating an even more efficient and inescapable \"digital poorhouse\"? This conversation would force a pragmatic visionary to confront the human consequences of automated decision-making at its most brutal. Featuring John Nay (Founder, Norm AI) & + Virginia Eubanks (Author, Automating Inequality).",
    "created_at": 1762017836207,
  },
  {
    "id": "87a00f4e-f062-4658-9626-5c0325a24d29",
    "title": "The Capital and The Culture: This discussion brings together two leaders who deploy capital to shape culture and drive social change, but who operate at vastly different scales and with divergent risk profiles",
    "description": "This discussion brings together two leaders who deploy capital to shape culture and drive social change, but who operate at vastly different scales and with divergent risk profiles. The conversation would be a meta-analysis of the podcast's own title, exploring the different strategies of 'Renegade Capital'. Darren Walker helms a multi-billion-dollar institution, working to steer its immense resources toward justice and equity from within the establishment. Christine Kuan leads a nimble organization founded specifically to fund the risk-taking, avant-garde artists that larger institutions might overlook. The guiding question is: What are the distinct and complementary roles of large-scale institutional philanthropy and agile, \"renegade\" funding in fostering a just and creatively vibrant society? Where do they overlap, and where must they necessarily diverge? This would be a masterclass in the strategy of social change through financial leverage. Featuring Darren Walker (President, Ford Foundation) & + Christine Kuan (President, Creative Capital).",
    "created_at": 1762017836900,
  },
  {
    "id": "77bd3f2e-0f54-4bf8-9e6a-79531b18c649",
    "title": "The Future of Human Labor (Part 1): The Economist's View",
    "description": "A three-episode series that examines the impact of AI on the future of work from three distinct and crucial perspectives: the macro-economist, the on-the-ground labor organizer, and the life-course strategist. The arc would begin with Daron Acemoglu, who can lay out the stark economic framework of automation's \"displacement effect\" on labor and the societal danger of the \"Turing Trap\". Featuring Daron Acemoglu.",
    "created_at": 1762017837553,
  },
  {
    "id": "2ed59538-7c76-4448-83ea-4827db13b65f",
    "title": "The Future of Human Labor (Part 2): The Worker's View",
    "description": "A three-episode series that examines the impact of AI on the future of work from three distinct and crucial perspectives: the macro-economist, the on-the-ground labor organizer, and the life-course strategist. Featuring , Ai-jen Poo.",
    "created_at": 1762017838182,
  },
  {
    "id": "6fbcb738-8861-43d3-8baa-44c9f8e57925",
    "title": "The Future of Human Labor (Part 3): The Life-Course View",
    "description": "A three-episode series that examines the impact of AI on the future of work from three distinct and crucial perspectives: the macro-economist, the on-the-ground labor organizer, and the life-course strategist. Featuring , and Lynda Gratton.",
    "created_at": 1762017838483,
  },
  {
    "id": "8740a11b-6f61-4390-af47-85a2c48d0cc1",
    "title": "The Builder and The Critic: This format moves beyond a simple debate to create a constructive dialogue between a leading AI founder and a premier critic of AI's social impact",
    "description": "This format moves beyond a simple debate to create a constructive dialogue between a leading AI founder and a premier critic of AI's social impact. The objective is to explore how deep critique can inform the foundational design philosophy of new technologies, moving ethics from a compliance checklist to a core product principle. Kanjun Qiu is building AI with the explicit goal of enhancing human agency and creativity. Ruha Benjamin's work meticulously documents how current technological systems often disempower and harm marginalized communities, and she offers \"abolitionist tools\" for a more just approach. The guiding question for this conversation is not \"Is AI good or bad?\" but rather: How could Benjamin's \"abolitionist tools\" be practically integrated into the architectural and ethical framework of an AI company like Imbue from its inception? This dialogue would transform a powerful critique into a potential design specification, offering a roadmap for a more equitable mode of AI development. Featuring Kanjun Qiu (CEO, Imbue) & + Ruha Benjamin (Author, Race After Technology).",
    "created_at": 1762017976808,
  },
  {
    "id": "a47b9cbf-77e4-4ef7-9e2e-c5c979c05d94",
    "title": "The Code and The Consequence: This pairing juxtaposes a technologist creating sophisticated, automated governance systems with a researcher who has documented the devastating real-world failures of similar systems",
    "description": "This pairing juxtaposes a technologist creating sophisticated, automated governance systems with a researcher who has documented the devastating real-world failures of similar systems. This grounds the promise of technical solutions in the lived experience of those most affected by their implementation. John Nay is building \"Regulatory AI\" to automate legal and regulatory compliance, aiming to create more efficient and auditable systems of governance. Virginia Eubanks' research provides a harrowing account of how automated welfare and social service systems have created a \"digital poorhouse,\" punishing the poor for minor errors and reinforcing systemic bias. The core tension to explore is: Can Nay's sophisticated, law-as-code approach be a genuine solution to the bureaucratic injustices Eubanks identifies, or does it risk creating an even more efficient and inescapable \"digital poorhouse\"? This conversation would force a pragmatic visionary to confront the human consequences of automated decision-making at its most brutal. Featuring John Nay (Founder, Norm AI) & + Virginia Eubanks (Author, Automating Inequality).",
    "created_at": 1762017977302,
  },
  {
    "id": "53e65be9-bd4b-4a62-a4d6-a1e5d43e60c1",
    "title": "The Capital and The Culture: This discussion brings together two leaders who deploy capital to shape culture and drive social change, but who operate at vastly different scales and with divergent risk profiles",
    "description": "This discussion brings together two leaders who deploy capital to shape culture and drive social change, but who operate at vastly different scales and with divergent risk profiles. The conversation would be a meta-analysis of the podcast's own title, exploring the different strategies of 'Renegade Capital'. Darren Walker helms a multi-billion-dollar institution, working to steer its immense resources toward justice and equity from within the establishment. Christine Kuan leads a nimble organization founded specifically to fund the risk-taking, avant-garde artists that larger institutions might overlook. The guiding question is: What are the distinct and complementary roles of large-scale institutional philanthropy and agile, \"renegade\" funding in fostering a just and creatively vibrant society? Where do they overlap, and where must they necessarily diverge? This would be a masterclass in the strategy of social change through financial leverage. Featuring Darren Walker (President, Ford Foundation) & + Christine Kuan (President, Creative Capital).",
    "created_at": 1762017978041,
  },
  {
    "id": "24547f25-ef7a-4413-9550-35808a685116",
    "title": "The Future of Human Labor (Part 1): The Economist's View",
    "description": "A three-episode series that examines the impact of AI on the future of work from three distinct and crucial perspectives: the macro-economist, the on-the-ground labor organizer, and the life-course strategist. The arc would begin with Daron Acemoglu, who can lay out the stark economic framework of automation's \"displacement effect\" on labor and the societal danger of the \"Turing Trap\". Featuring Daron Acemoglu.",
    "created_at": 1762017978558,
  },
  {
    "id": "9a8a4e82-a3a5-4b62-acbf-10d06211bb86",
    "title": "The Future of Human Labor (Part 2): The Worker's View",
    "description": "A three-episode series that examines the impact of AI on the future of work from three distinct and crucial perspectives: the macro-economist, the on-the-ground labor organizer, and the life-course strategist. Featuring , Ai-jen Poo.",
    "created_at": 1762017979117,
  },
  {
    "id": "cc1e4c40-99c0-4761-9b9d-eeb5880be262",
    "title": "The Future of Human Labor (Part 3): The Life-Course View",
    "description": "A three-episode series that examines the impact of AI on the future of work from three distinct and crucial perspectives: the macro-economist, the on-the-ground labor organizer, and the life-course strategist. Featuring , and Lynda Gratton.",
    "created_at": 1762017979484,
    "updated_at": NaN
  }
];

export const research = [
  {
    "id": "1a69902b-7312-4828-9b9f-d4899f5d8117",
    "name": "Joy Buolamwini",
    "domain": "AI Ethics",
    "chemistry": "Visionary",
    "topic": "Algorithmic Justice and Financial Equity",
    "link": "https://www.ajlunited.org",
    "date_added": 1760486400,
    "created_at": 1762017408196,
    "headshot_url": null    
  },
  {
    "id": "25cafc25-5f19-440b-af38-a22d5f4f0082",
    "name": "Ruha Benjamin",
    "domain": "Science & Technology Studies",
    "chemistry": "Critical Thinker",
    "topic": "Race After Technology: Abolitionist Tools for the New Jim Code",
    "link": "https://www.ruhabenjamin.com",
    "date_added": 1760572800,
    "created_at": 1762017408594,
    "affiliation": "Princeton University",
    "headshot_url": "Hosted within press kit via https://www.ruhabenjamin.com/media"
  },
  {
    "id": "94e5d92a-8e50-4e58-9f51-9c6b318dee86",
    "name": "Timnit Gebru",
    "domain": "AI Research",
    "chemistry": "Truth-Teller",
    "topic": "Data Colonialism and AI Accountability",
    "link": "https://www.dair-institute.org",
    "date_added": 1760745600,
    "created_at": 1762017409033,
    "headshot_url": null    
  },
  {
    "id": "b4732422-0084-4bb4-b666-105a9aff752a",
    "name": "Safiya Umoja Noble",
    "domain": "Information Studies",
    "chemistry": "Analytical",
    "topic": "Algorithms of Oppression: How Search Engines Reinforce Racism",
    "link": "https://safiyaunoble.com",
    "date_added": 1760918400,
    "created_at": 1762017409502,
    "affiliation": "UCLA Center on Race & Digital Justice",
    "headshot_url": "https://gender.ucla.edu/wp-content/uploads/2019/04/S_Noble.jpg"
  },
  {
    "id": "77e00d50-d746-4e4a-83f0-a06aae7de50b",
    "name": "Cathy O'Neil",
    "domain": "Data Science",
    "chemistry": "Pragmatist",
    "topic": "Weapons of Math Destruction: How Big Data Increases Inequality",
    "link": "https://mathbabe.org",
    "date_added": 1761091200,
    "created_at": 1762017409986,
    "headshot_url": null
  },
  {
    "id": "0dc6f6d9-0860-429f-9f95-d51b41322050",
    "name": "Joy Buolamwini",
    "domain": "AI Ethics",
    "chemistry": "Visionary",
    "topic": "Algorithmic Justice and Financial Equity",
    "link": "https://www.ajlunited.org",
    "date_added": 1760486400,
    "created_at": 1762017587222,
    "headshot_url": null
  },
  {
    "id": "18b51871-5a42-4337-bde8-bb5797d4bda8",
    "name": "Ruha Benjamin",
    "domain": "Science & Technology Studies",
    "chemistry": "Critical Thinker",
    "topic": "Race After Technology: Abolitionist Tools for the New Jim Code",
    "link": "https://www.ruhabenjamin.com",
    "date_added": 1760572800,
    "created_at": 1762017587675,
    "affiliation": "Princeton University",
    "headshot_url": "https://sites.uci.edu/forum/2020/01/03/ruha-benjamin-race-after-technology-feb-7-2020/"
  },
  {
    "id": "882bd0a7-5e34-43f5-9044-3836fa8b029e",
    "name": "Timnit Gebru",
    "domain": "AI Research",
    "chemistry": "Truth-Teller",
    "topic": "Data Colonialism and AI Accountability",
    "link": "https://www.dair-institute.org",
    "date_added": 1760745600,
    "created_at": 1762017587960,
    "headshot_url": null
  },
  {
    "id": "d76b3f65-1ffb-41ec-ae85-0dc41d2b9875",
    "name": "Safiya Umoja Noble",
    "domain": "Information Studies",
    "chemistry": "Analytical",
    "topic": "Algorithms of Oppression: How Search Engines Reinforce Racism",
    "link": "https://safiyaunoble.com",
    "date_added": 1760918400,
    "created_at": 1762017588325,
    "affiliation": "UCLA Center on Race & Digital Justice",
    "headshot_url": "https://gender.ucla.edu/wp-content/uploads/2019/04/S_Noble.jpg"
  },
  {
    "id": "226c441c-94d1-4818-9a05-015ecf4fc115",
    "name": "Cathy O'Neil",
    "domain": "Data Science",
    "chemistry": "Pragmatist",
    "topic": "Weapons of Math Destruction: How Big Data Increases Inequality",
    "link": "https://mathbabe.org",
    "date_added": 1761091200,
    "created_at": 1762017588695,
    "headshot_url": null
  },
  {
    "id": "9e3def0a-1c97-4ff1-971f-406e4b0ba266",
    "name": "Joy Buolamwini",
    "domain": "AI Ethics",
    "chemistry": "Visionary",
    "topic": "Algorithmic Justice and Financial Equity",
    "link": "https://www.ajlunited.org",
    "date_added": 1760486400,
    "created_at": 1762017722822,
    "headshot_url": null
  },
  {
    "id": "c21883a4-19cf-46f4-9307-f37155a7db89",
    "name": "Ruha Benjamin",
    "domain": "Science & Technology Studies",
    "chemistry": "Critical Thinker",
    "topic": "Race After Technology: Abolitionist Tools for the New Jim Code",
    "link": "https://www.ruhabenjamin.com",
    "date_added": 1760572800,
    "created_at": 1762017723240,
    "updated_at": NaN,
    "affiliation": "Princeton University",
    "headshot_url": "https://sites.uci.edu/forum/2020/01/03/ruha-benjamin-race-after-technology-feb-7-2020/"
  }
];

export const guests = [
  {
    "id": "53f62237-24a6-4249-8154-faad535c37de",
    "name": "Kate Crawford",
    "persona_description": "The leading cross-disciplinary critic of AI's planetary and political costs. Crawford is arguably the most important cross-disciplinary critic of artificial intelligence today. Her work fundamentally reframes the discourse, moving it away from a narrow focus on algorithms and toward a comprehensive analysis of AI as a form of extractive power. Her book, Atlas of AI, meticulously documents the material costs of the industry\u2014from the environmental devastation of lithium mining for batteries to the exploitation of low-wage data labelers and the immense energy footprint of data centers. This \"planetary scale\" perspective directly integrates the podcast's core themes of AI, finance (capital accumulation and resource extraction), and social justice (labor rights, environmental justice). An appearance would provide a foundational, systems-level critique that is essential for any serious discussion of technology's societal impact. Chemistry Tag: The Systems Thinker. Expect a sweeping, macro-level conversation that connects disparate dots\u2014geopolitics, labor history, geology, and computer science\u2014with academic rigor and profound insight. She can elevate a technical conversation into a political and philosophical one. Potential Topic: \"The Atlas of AI: Exposing the Hidden Planetary Costs of the Computational Empire.\"",
    "expertise": "AI & Society, Politics, Environment.",
    "tone": "The Systems Thinker. Expect a sweeping, macro-level conversation that connects disparate dots\u2014geopolitics, labor history, geology, and computer science\u2014with academic rigor and profound insight. She can elevate a technical conversation into a political and philosophical one.",
    "background": "Audience: Academic, Policy Wonks, Ethically-Minded Tech Professionals, Environmental Activists. | Influence: Public Intellectual.",
    "created_at": 1762017826021,
    "is_book_contributor": 0,
    "affiliation": "USC / Microsoft Research",
    "headshot_url": "https://images.squarespace-cdn.com/content/v1/655cb99992574744b5a625e4/f960adf2-174d-4c49-aa2c-abdb49983c2a/katephoto_cath_muscat_scaled.png"
  },
  {
    "id": "8c9f4801-d8ed-4b8a-9718-e36b4ee38022",
    "name": "Ruha Benjamin",
    "persona_description": "Originator of the \"New Jim Code\" framework for understanding tech and racial bias. Benjamin's work provides one of the most powerful and widely adopted frameworks for understanding the intersection of technology and racial injustice. By coining the term \"The New Jim Code,\" she draws a direct line from historical systems of racial control to the seemingly neutral algorithms of today, arguing that technology can be a powerful force for deepening, rather than solving, social hierarchies. Her book Race After Technology is a cornerstone of the critical tech field, offering \"abolitionist tools\" for dismantling discriminatory design. An interview with Benjamin would ground the podcast's exploration of AI in the long history of racial struggle and provide listeners with a sharp, actionable vocabulary for critique. Chemistry Tag: The Abolitionist Scholar. Incisive, historically grounded, and forward-looking. She connects contemporary tech criticism to broader, more radical movements for social liberation, challenging techno-solutionist narratives with a call for systemic change. Potential Topic: \"Race After Technology: Unmasking and Dismantling the 'New Jim Code' in Our Algorithms.\"",
    "expertise": "Sociology, African American Studies, Science & Technology Studies.",
    "tone": "The Abolitionist Scholar. Incisive, historically grounded, and forward-looking. She connects contemporary tech criticism to broader, more radical movements for social liberation, challenging techno-solutionist narratives with a call for systemic change.",
    "background": "Audience: Social Justice Advocates, Academics, DEI Leaders in Tech, Activists. | Influence: Public Intellectual.",
    "created_at": 1762017826375,
    "is_book_contributor": 0,
    "affiliation": "Princeton University",
    "headshot_url": "Hosted within press kit via https://www.ruhabenjamin.com/media"
  },
  {
    "id": "31888dd1-ace9-4d4a-8078-8fc52e7b0956",
    "name": "Safiya Umoja Noble",
    "persona_description": "Foundational scholar on how search engines reinforce racism and sexism. Noble's groundbreaking book Algorithms of Oppression was one of the first to provide rigorous, scholarly proof of what many users had long suspected: commercial search engines are not neutral windows onto the world but are deeply biased systems that reinforce racism and sexism. Her research, which began with the discovery that a search for \"black girls\" yielded predominantly pornographic results, exposed the commercial incentives and cultural assumptions that shape our information ecosystem. As a MacArthur Fellow and a leading voice on algorithmic discrimination, she is a foundational figure whose work remains essential for understanding how technology shapes public perception and perpetuates harm. Chemistry Tag: The Digital Archivist. Meticulous and evidence-based, she can unpack the hidden histories, commercial imperatives, and technical decisions that lead to discriminatory outcomes online. Her approach is less about polemic and more about presenting irrefutable evidence. Potential Topic: \"Algorithms of Oppression: How Google and the Commercial Web Reinforce Racism.\"",
    "expertise": "Information Studies, Gender Studies, Algorithmic Bias.",
    "tone": "The Digital Archivist. Meticulous and evidence-based, she can unpack the hidden histories, commercial imperatives, and technical decisions that lead to discriminatory outcomes online. Her approach is less about polemic and more about presenting irrefutable evidence.",
    "background": "Audience: General Intellectually Curious, Media Consumers, Librarians/Information Professionals, Marketing Professionals. | Influence: Public Intellectual.",
    "created_at": 1762017826792,
    "is_book_contributor": 0,
    "affiliation": "UCLA Center on Race & Digital Justice",
    "headshot_url": "https://gender.ucla.edu/wp-content/uploads/2019/04/S_Noble.jpg"
  },
  {
    "id": "34eb3e88-47e5-4ac1-9396-769985e59783",
    "name": "Meredith Broussard",
    "persona_description": "A practitioner-critic who makes complex algorithmic bias accessible and tangible. Broussard brings a rare and valuable combination of skills: she is a trained data scientist and software developer who is also a gifted journalist and critic. This dual expertise allows her to demystify complex technical concepts for a general audience without sacrificing rigor. Her book More Than a Glitch argues against \"technochauvinism\"\u2014the belief that technology is always the best solution\u2014and provides concrete examples of how biased systems are built and deployed. As one of the few Black female researchers in AI and a featured expert in the documentary Coded Bias, she offers a crucial practitioner's perspective on the fight for equitable technology. Chemistry Tag: The Translator. She excels at breaking down the inner workings of code and data science for a non-technical audience. The conversation would be grounded in compelling, real-world examples, from racist soap dispensers to biased mortgage algorithms. Potential Topic: \"More Than a Glitch: Why Neutrality in Tech is a Myth and How to Fight 'Technochauvinism'.\"",
    "expertise": "Data Journalism, AI Ethics, Algorithmic Accountability.",
    "tone": "The Translator. She excels at breaking down the inner workings of code and data science for a non-technical audience. The conversation would be grounded in compelling, real-world examples, from racist soap dispensers to biased mortgage algorithms.",
    "background": "Audience: Journalists, Aspiring Data Scientists, General Audience, Tech Professionals seeking ethical grounding. | Influence: Industry Leader.",
    "created_at": 1762017827177,
    "is_book_contributor": 0,
    "affiliation": "New York University / UM-Flint",
    "headshot_url": "https://news.umflint.edu/2024/03/19/nyu-professor-meredith-broussard-to-discuss-bias-in-technology-march-27/"
  },
  {
    "id": "8a2dc201-5104-45a3-85e6-81f436c1c6be",
    "name": "Virginia Eubanks",
    "persona_description": "Investigative storyteller documenting the \"digital poorhouse\" and its human cost. While many critiques of AI focus on abstract harms, Eubanks' work makes the consequences visceral and undeniable. Her landmark book, Automating Inequality, is a feat of investigative reporting that documents the creation of a \"digital poorhouse\" through three deeply researched case studies of automated welfare, homeless services, and child protection systems. She tells the heart-wrenching stories of individuals whose lives have been devastated by flawed algorithms and data-driven systems. This approach powerfully connects the podcast's themes of technology and social justice to the distribution of public funds and the policing of the poor, making her an essential voice for grounding the debate in human reality. Chemistry Tag: The Investigative Storyteller. A conversation with Eubanks would be rooted in powerful, emotional, and often infuriating narratives. She is a passionate advocate who uses storytelling as a tool for political and social change. Potential Topic: \"Automating Inequality: Inside the Digital Poorhouse and the Human Cost of Flawed Algorithms.\"",
    "expertise": "Political Science, Technology, Poverty & Social Justice.",
    "tone": "The Investigative Storyteller. A conversation with Eubanks would be rooted in powerful, emotional, and often infuriating narratives. She is a passionate advocate who uses storytelling as a tool for political and social change.",
    "background": "Audience: Policy Makers, Social Workers, Activists, Civil Liberties Advocates, General Audience. | Influence: Public Intellectual.",
    "created_at": 1762017827492,
    "is_book_contributor": 0,
    "headshot_url": null
  },
  {
    "id": "be5d1e99-afc4-46e4-87ce-9df60bf69c7b",
    "name": "Marzyeh Ghassemi",
    "persona_description": "A leading builder of fair and robust AI systems for high-stakes healthcare applications. Ghassemi represents the cutting edge of constructive AI ethics. As an Associate Professor at MIT and head of the \"Healthy ML\" group, her research focuses on the formidable challenge of building machine learning models for healthcare that are robust, private, and fair. Her work tackles issues like underdiagnosis bias in algorithms applied to underserved populations and the false hope of current \"explainable AI\" methods. She moves the conversation beyond critique to the practical, high-stakes work of designing and deploying equitable AI in a domain where the consequences are life and death. Her numerous awards, including a Sloan Research Fellowship and being named one of MIT Tech Review's 35 Innovators Under 35, attest to her leadership in the field. Chemistry Tag: The Rigorous Builder. A deeply technical but exceptionally clear-headed expert. She can articulate the nuanced trade-offs and immense difficulties of implementing fair AI in complex, real-world systems, grounding the conversation in data and peer-reviewed research. Potential Topic: \"Building 'Healthy' AI: The Fight for Fairness and Robustness in Medical Machine Learning.\"",
    "expertise": "AI in Healthcare, Machine Learning, Health Equity.",
    "tone": "The Rigorous Builder. A deeply technical but exceptionally clear-headed expert. She can articulate the nuanced trade-offs and immense difficulties of implementing fair AI in complex, real-world systems, grounding the conversation in data and peer-reviewed research.",
    "background": "Audience: Tech Professionals, Healthcare Innovators, Bioethicists, Data Scientists. | Influence: Industry Leader.",
    "created_at": 1762017827903,
    "is_book_contributor": 0,
    "affiliation": "MIT CSAIL / Jameel Clinic",
    "headshot_url": "https://www.csail.mit.edu/sites/default/files/styles/headshot/public/images/people/profile/IMG_3006.jpeg?h=88c62e36&itok=hf_XXeeJ"
  },
  {
    "id": "19890d52-075b-4fe8-a8aa-de1fa6567c9f",
    "name": "Nita Farahany",
    "persona_description": "A legal futurist defining the coming battle for \"cognitive liberty\" and mental privacy. Farahany is a leading scholar on the legal and ethical implications of emerging technologies, particularly at the intersection of neuroscience and AI. Her recent book, The Battle for Your Brain, makes a compelling case for establishing \"cognitive liberty\" as a fundamental human right. She argues that as neurotechnology becomes more pervasive\u2014in consumer wearables, workplaces, and even legal systems\u2014our very freedom of thought is at risk. This is a provocative, forward-looking theme that pushes the boundaries of the current AI ethics debate from data privacy to mental privacy, a truly 'renegade' concept that is perfect for the podcast. Chemistry Tag: The Legal Futurist. Eloquent and urgent, she can paint a vivid, and at times terrifying, picture of a near-future legal and ethical battleground. She excels at making speculative threats feel immediate and tangible, backed by her deep expertise in law and bioethics. Potential Topic: \"The Battle for Your Brain: Defending Cognitive Liberty in the Age of AI and Neurotech.\"",
    "expertise": "Law, Neuroscience, AI Ethics, Bioethics.",
    "tone": "The Legal Futurist. Eloquent and urgent, she can paint a vivid, and at times terrifying, picture of a near-future legal and ethical battleground. She excels at making speculative threats feel immediate and tangible, backed by her deep expertise in law and bioethics.",
    "background": "Audience: Legal Professionals, Futurists, Civil Liberties Advocates, Tech Ethicists. | Influence: Public Intellectual.",
    "created_at": 1762017828236,
    "is_book_contributor": 0
    "headshot_url": null
  },
  {
    "id": "346a40a8-938b-4a46-92d8-216b7dd2ca61",
    "name": "John Nay",
    "persona_description": "Founder building market-based solutions to automate AI alignment using legal code. Nay offers a novel and pragmatic approach to the problem of AI governance. As the founder of Norm AI and a fellow at Stanford's CodeX, he is a pioneer in the field of \"Legal Informatics,\" which treats legal and regulatory text as data to train and align AI systems. His company builds \"Regulatory AI agents\" designed to automate compliance, aiming to solve both the costly \"sludge\" of bureaucracy and the societal-AI alignment problem. This represents a market-based, scalable solution to AI safety, perfectly blending the podcast's focus on finance, technology, and social governance. He is a builder who is actively trying to code ethics into enterprise systems. Chemistry Tag: The Pragmatic Visionary. A founder and researcher who can speak with authority on both the deep technical challenges of AI alignment and the massive market opportunity in building trustworthy AI. He bridges the gap between academic theory and venture-backed execution. Potential Topic: \"From Law to Code: Can We Automate AI Alignment and Solve the 'Sludge' Problem?\"",
    "expertise": "AI & Law, Regulatory Tech, Entrepreneurship.",
    "tone": "The Pragmatic Visionary. A founder and researcher who can speak with authority on both the deep technical challenges of AI alignment and the massive market opportunity in building trustworthy AI. He bridges the gap between academic theory and venture-backed execution.",
    "background": "Audience: VCs, Fintech Professionals, Legal Tech Enthusiasts, Regulators, AI Safety Researchers. | Influence: Industry Leader.",
    "created_at": 1762017828580,
    "is_book_contributor": 0,
    "affiliation": "Norm AI / Stanford Law",
    "headshot_url": "https://conferences.law.stanford.edu/futurelaw2024/wp-content/uploads/sites/166/2024/03/Nay_John.jpg"
  },
  {
    "id": "f7838094-2945-4d39-a4be-181abc53c3b2",
    "name": "Shannon Vallor",
    "persona_description": "A leading voice on how AI is reshaping human virtue, character, and morality. Vallor brings a much-needed philosophical depth to the technology conversation. As the Baillie Gifford Chair in the Ethics of Data and AI at the University of Edinburgh, her work moves beyond questions of bias and fairness to explore a more fundamental issue: how our increasing reliance on AI and robotics is reshaping our moral character, habits, and virtues. Her book The AI Mirror argues for using this technological moment as an opportunity to reclaim our humanity. A conversation with Vallor would elevate the podcast's discourse from policy and code to the very nature of a \"future worth wanting\". Chemistry Tag: The Moral Philosopher. Thoughtful, reflective, and foundational. She will challenge the host and audience to think about technology's impact on a deeper, more personal, and existential level, prompting reflection on our own habits and values. Potential Topic: \"The AI Mirror: Reclaiming Human Virtue in an Age of Machine Thinking.\"",
    "expertise": "Philosophy of Technology, AI Ethics, Virtue Ethics.",
    "tone": "The Moral Philosopher. Thoughtful, reflective, and foundational. She will challenge the host and audience to think about technology's impact on a deeper, more personal, and existential level, prompting reflection on our own habits and values.",
    "background": "Audience: Academics, Ethicists, Theologians, Intellectually Curious Generalists. | Influence: Public Intellectual.",
    "created_at": 1762017828815,
    "is_book_contributor": 0,
    "affiliation": "University of Edinburgh",
    "headshot_url": "https://www.audible.com/author/Shannon-Vallor/B01LY76PK2?srsltid=AfmBOoocI48wF1bsx948dGPYi1X872QEbQ2vxaU5yv8cuH7jAIkZoNSW"
  },
  {
    "id": "2c9b6505-b524-41b7-8cc7-8bcffe33d3a1",
    "name": "Daron Acemoglu",
    "persona_description": "A top economist offering a critical, data-driven perspective on automation's true impact on labor. Acemoglu is one of the world's most cited economists and a leading authority on the economic impacts of technology and automation. His research provides a crucial, data-driven counter-narrative to the hype surrounding AI's productivity benefits. He argues that automation has a powerful \"displacement effect\" on labor that is not always offset by the creation of new tasks. He warns against falling into the \"Turing Trap,\" where the focus on creating AI that merely mimics and replaces human labor drives down wages and increases inequality, rather than augmenting human capabilities to create new value. His perspective is essential for grounding the AI conversation in the realities of the labor market. Chemistry Tag: The Skeptical Economist. Data-driven, rigorous, and unafraid to challenge prevailing narratives. He can cut through the marketing claims of AI companies to discuss the real, and often negative, consequences for workers and the broader economy. Potential Topic: \"Escaping the Turing Trap: Why Augmenting Workers, Not Replacing Them, is the Future of AI.\"",
    "expertise": "Economics, Automation, Labor Markets.",
    "tone": "The Skeptical Economist. Data-driven, rigorous, and unafraid to challenge prevailing narratives. He can cut through the marketing claims of AI companies to discuss the real, and often negative, consequences for workers and the broader economy.",
    "background": "Audience: Economists, Policy Makers, Business Leaders, Labor Advocates, Finance Professionals. | Influence: Public Intellectual.",
    "created_at": 1762017829100,
    "is_book_contributor": 0,
    "affiliation": "MIT / Nobel Committee",
    "headshot_url": "https://en.wikipedia.org/wiki/Daron_Acemoglu"
  },
  {
    "id": "e4674428-865a-4b61-84dd-8525b14cd969",
    "name": "Darren Walker",
    "persona_description": "Leader of a major philanthropic institution deploying capital for social justice at scale. As President of the Ford Foundation, Darren Walker sits at the nexus of immense capital and the drive for social justice. He has been a leading voice in pushing philanthropy to confront inequality more directly and to use its financial power\u2014not just its grantmaking\u2014to effect change. He can speak with unparalleled authority on how major financial institutions are grappling with the challenges posed by technology, threats to democracy, and systemic inequality. An interview with Walker would offer a macro-view of 'Renegade Capital' in action, but from within one of the world's most established and influential institutions. Chemistry Tag: The Statesman. Polished, articulate, and deeply strategic. He can provide a high-level, institutional perspective on how to drive radical change, bridging the worlds of Wall Street, non-profits, and grassroots activism. Potential Topic: \"Capital as a Tool for Justice: How the Ford Foundation is Funding the Fight for a More Equitable Future.\"",
    "expertise": "Philanthropy, Social Justice, Finance.",
    "tone": "The Statesman. Polished, articulate, and deeply strategic. He can provide a high-level, institutional perspective on how to drive radical change, bridging the worlds of Wall Street, non-profits, and grassroots activism.",
    "background": "Audience: Non-profit Leaders, Philanthropists, Finance Professionals, Policy Makers. | Influence: Global Leader.",
    "created_at": 1762017829465,
    "is_book_contributor": 0,
    "affiliation": "Ford Foundation",
    "headshot_url": "https://gcp-na-images.contentstack.com/v3/assets/bltea6093859af6183b/blte54e0c028c224cdf/6998cd01e1ba0036a098e467/time-closers-2026-darren-walker-01.jpg?branch=production&width=3840&quality=75&auto=webp&crop=4:5"
  },
  {
    "id": "252c739e-3002-40d5-bcff-6e0d6e3222f2",
    "name": "Ai-jen Poo",
    "persona_description": "A MacArthur-winning organizer representing the workers most affected by the future of work. Ai-jen Poo is one of the most effective and celebrated labor organizers of her generation. As President of the National Domestic Workers Alliance and a recipient of a MacArthur \"Genius\" Grant, she has been at the forefront of fighting for rights and recognition for the care workforce\u2014a sector dominated by women of color and immigrants, and one profoundly affected by the gig economy and the specter of automation. She brings the essential, human-centered perspective of the workers whose lives are most directly shaped by the technological and economic shifts discussed on the podcast. Her work with Caring Across Generations also connects labor rights to the broader social challenge of an aging population. Chemistry Tag: The Grassroots Organizer. Passionate, clear, and grounded in the real stories and struggles of workers. She is a powerful moral voice who can translate complex policy debates into urgent human terms. Potential Topic: \"The Future of Care: Organizing for Dignity in the Age of Automation and the Gig Economy.\"",
    "expertise": "Labor Activism, Social Justice, Future of Work.",
    "tone": "The Grassroots Organizer. Passionate, clear, and grounded in the real stories and struggles of workers. She is a powerful moral voice who can translate complex policy debates into urgent human terms.",
    "background": "Audience: Activists, Labor Organizers, Social Justice Advocates, Policy Makers. | Influence: Public Intellectual.",
    "created_at": 1762017829756,
    "is_book_contributor": 0,
    "affiliation": "National Domestic Workers Alliance",
    "headshot_url": "https://upload.wikimedia.org/wikipedia/commons/4/41/Ai-jen_Poo%2C_National_Domestic_Workers_Alliance%2C_2015.jpg"
  },
  {
    "id": "b4e886e0-345b-4d92-aa51-10d4543c19c3",
    "name": "Lauren Maffeo",
    "persona_description": "An on-the-ground practitioner implementing responsible AI policy in state government. Maffeo represents the new generation of public servants tasked with implementing AI responsibly. As a Senior Program Manager for AI/ML in the State of Maryland and a member of the Aspen Institute's \"Rising Civic AI Leaders\" initiative, she is on the front lines of translating high-level ethical principles into workable government policy. Her experience includes leading service design in the Coast Guard's first Chief Data and AI Office and authoring a book on data governance. She offers a tangible, \"how the sausage gets made\" perspective that is often missing from theoretical discussions of AI ethics. Chemistry Tag: The Civic Implementer. Practical, articulate, and deeply knowledgeable about the challenges of bridging the gap between high-level policy goals and the on-the-ground technical and bureaucratic realities of public sector work. Potential Topic: \"From the Ground Up: The Messy Reality of Implementing Ethical AI in State Government.\"",
    "expertise": "Civic Tech, AI Governance, Public Policy.",
    "tone": "The Civic Implementer. Practical, articulate, and deeply knowledgeable about the challenges of bridging the gap between high-level policy goals and the on-the-ground technical and bureaucratic realities of public sector work.",
    "background": "Audience: Public Sector Employees, Civic Tech Community, Policy Students, Government Contractors. | Influence: Niche Expert.",
    "created_at": 1762017830049,
    "is_book_contributor": 0,
    "affiliation": "State of Maryland",
    "headshot_url": "https://www.aspendigital.org/wp-content/uploads/2025/10/LM-CB-Headshot-Lauren-Maffeo-e1759960099604.webp"
  },
  {
    "id": "a4fb547a-ed06-4889-9f1e-a99d441c2012",
    "name": "Karen Hao",
    "persona_description": "The definitive inside-chronicler of OpenAI and the global race for AI dominance. Hao is an award-winning journalist who has established herself as the definitive chronicler of the current AI boom. Having covered OpenAI with unparalleled access from its early days, her book Empire of AI provides a critical, inside account of the personalities, power dynamics, and global ambitions driving the race for artificial general intelligence. Her reporting spans continents, connecting the corporate boardrooms of Silicon Valley to the data workers in the Global South and the immense environmental costs of AI's infrastructure. As a trainer for the Pulitzer Center's AI Spotlight Series, she is also shaping how the next generation of journalists covers this crucial topic. Chemistry Tag: The Insider Chronicler. A sharp, investigative journalist with deep sourcing and a clear-eyed perspective. She can tell the behind-the-scenes story of the AI revolution with nuance and a healthy dose of skepticism, cutting through the industry's carefully crafted narratives. Potential Topic: \"Empire of AI: Inside the Power, Hype, and Hidden Costs of the Race for AGI.\"",
    "expertise": "Journalism, AI, China Tech.",
    "tone": "The Insider Chronicler. A sharp, investigative journalist with deep sourcing and a clear-eyed perspective. She can tell the behind-the-scenes story of the AI revolution with nuance and a healthy dose of skepticism, cutting through the industry's carefully crafted narratives.",
    "background": "Audience: Tech Insiders, VCs, Journalists, Policy Makers, General Audience. | Influence: Industry Leader.",
    "created_at": 1762017830369,
    "is_book_contributor": 0,
    "affiliation": "Investigative Journalist / Author",
    "headshot_url": "https://images.squarespace-cdn.com/content/v1/64a4ee85e22ab3529f73f53f/615dcd4d-93a7-47ad-9e65-23b3a8b3c9cf/KarenHao.jpg"
  },
  {
    "id": "add71b23-706b-4336-b187-95cd93199658",
    "name": "Mo Wang",
    "persona_description": "A researcher applying the science of human behavior to the future of work and aging. Dr. Mo Wang is a University Distinguished Professor at the University of Florida and a leading researcher on the human side of the future of work. His expertise in occupational health psychology and the employment of older workers provides a crucial behavioral science lens on how automation and AI will affect the workforce. While economists like Acemoglu focus on the macro-level labor market, Wang can speak to the psychological impacts: How does AI change motivation? How do teams function with automated members? How do we ensure \"successful aging in the workplace\" when skills are constantly becoming obsolete? This connects the abstract future of work to the tangible, human experience of it. Chemistry Tag: The People Scientist. An academic expert who can translate complex, peer-reviewed research on human behavior, motivation, and aging into practical insights for leaders, HR professionals, and individual workers navigating career transitions. Potential Topic: \"The Psychology of an Automated Workplace: How Will AI Change the Way We Age, Work, and Retire?\"",
    "expertise": "Behavioral Economics, Future of Work, Occupational Psychology.",
    "tone": "The People Scientist. An academic expert who can translate complex, peer-reviewed research on human behavior, motivation, and aging into practical insights for leaders, HR professionals, and individual workers navigating career transitions.",
    "background": "Audience: HR Professionals, Business Leaders, Policy Makers, Organizational Psychologists. | Influence: Niche Expert.",
    "created_at": 1762017830678,
    "is_book_contributor": 0,
    "affiliation": "University of Florida",
    "headshot_url": "https://b768902a.delivery.rocketcdn.me/wp-content/uploads/profiles/mo-wang-5309-3x4.jpg"
  },
  {
    "id": "8a67620f-9516-4b5c-bc5c-4e138ae28396",
    "name": "Christoph Nedopil Wang",
    "persona_description": "An authority on the global financial flows shaping sustainable development and climate action. Nedopil is an authority on the intersection of global finance and sustainability. As Director of the Green Finance & Development Center, his work focuses on green innovation finance, particularly in the context of China's massive Belt and Road Initiative (BRI) and other emerging economies. He can speak with deep expertise on how trillions of dollars in global capital are being directed, and whether those investments are accelerating or hindering the green transition. His perspective is vital for connecting the podcast's finance and social justice themes on a global, geopolitical scale, examining whether capital can truly be a force for climate action. Chemistry Tag: The Global Economist. Data-driven and policy-focused, able to dissect the complex macro-economic trends, geopolitical incentives, and financial instruments that are shaping the future of sustainable development worldwide. Potential Topic: \"Greening the New Silk Road: Can Global Finance Be Steered to Avert Climate Catastrophe?\"",
    "expertise": "Green Finance, Sustainable Development, Climate Tech.",
    "tone": "The Global Economist. Data-driven and policy-focused, able to dissect the complex macro-economic trends, geopolitical incentives, and financial instruments that are shaping the future of sustainable development worldwide.",
    "background": "Audience: International Relations Specialists, Climate Investors, Policy Makers, ESG Professionals. | Influence: Industry Leader. III. The Stretch Guest List: Expanding Horizons and Attracting New Listeners This list of 12 guests is designed to be provocative and expansive. These individuals are innovators, artists, and thinkers operating at the edges of the core debate. They are chosen to introduce novel concepts, challenge audience assumptions, and bring a creative, sometimes unconventional, energy to the podcast. Booking these guests will signal the podcast's intellectual curiosity and help attract new listener demographics from the worlds of art, philosophy, and deep-tech innovation. | Guest Name | Domain | Unique Angle | |---|---|---| | Kanjun Qiu | AI Entrepreneurship | The \"Philosopher-CEO\" building AI to enhance human agency and potential. | | Sougwen Chung | Art & Robotics | An artist who physically collaborates with robots to explore human-machine creativity. | | Jake Elwes | Art & Queer Theory | A media artist using deepfake drag performance to \"queer\" and subvert AI systems. | | Christine Kuan | Arts Funding & Philanthropy | The leader of a foundation that acts as a venture capitalist for radical, socially-engaged art. | | Neil Harbisson | Cyborg Art & Activism | The world's first legally recognized cyborg, challenging the definition of \"human.\" | | Rodney Foxworth | Social Entrepreneurship | A leader in \"restorative economics\" focused on shifting capital and power to communities. | | Nneka Sobers | Civic Tech & Urban Design | A civic innovator who co-designs urban technology with local communities. | | Kalonji Gilchrist | Arts & Community Organizing | A cultural activator using public art to reclaim history and drive social justice in the South. | | Lynda Gratton | Future of Work & Longevity | A business professor arguing for a radical reinvention of the human life-course. | | Dr. Caroline Smith | Labor Equity & Public Health | A researcher who co-creates policy solutions by centering the voices of underserved workers. | | Sampriti Bhattacharyya | Deep Tech Entrepreneurship | A founder building tangible, zero-emission \"flying boats\" at the nexus of AI and climate tech. | | Dawn Laguens | Social Innovation & Design | A leader who bridges high-stakes political strategy with human-centered design thinking. | Detailed Guest Profiles",
    "created_at": 1762017830999,
    "is_book_contributor": 0,
    "affiliation": "Green Finance & Development Center",
    "headshot_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1i-uCVvcbxGbf3JFQYJwNjx7FhYmnqjtQvw&s"
  },
  {
    "id": "82fc44b7-b93f-4833-b348-a22a48f561b7",
    "name": "Kanjun Qiu",
    "persona_description": "Qiu represents a fundamentally different kind of AI founder. While many in the field are focused on metrics and scale, her work with her AI lab, Imbue, is driven by a deep curiosity about foundational humanistic questions: What is knowledge? What is culture? What determines a person's sense of agency?. Her stated mission is to \"rekindle the dream of the personal computer\" by creating AI agents that serve as tools for human creativity and empowerment, rather than mere replacement. This philosophical, human-centric vision for AI is a truly 'renegade' stance within Silicon Valley, making her a perfect stretch guest to challenge and inspire the audience. Chemistry Tag: The Philosopher-CEO. An intellectually expansive and deeply curious guest who can move fluidly between the technical details of building AI agents and profound questions about the nature of consciousness, creativity, and what it means to live a meaningful life. Potential Topic: \"Beyond the Code: Building AI to Unlock Human Agency and Potential.\"",
    "expertise": "AI Entrepreneurship, Philosophy of Mind, Human Potential.",
    "tone": "The Philosopher-CEO. An intellectually expansive and deeply curious guest who can move fluidly between the technical details of building AI agents and profound questions about the nature of consciousness, creativity, and what it means to live a meaningful life.",
    "background": "Audience: Tech Founders, Philosophers, Futurists, VCs looking for the next paradigm. | Influence: Industry Leader.",
    "created_at": 1762017831344,
    "is_book_contributor": 0,
    "headshot_url": "https://images.squarespace-cdn.com/content/v1/6455de661f40b056133ed927/3e1dbb7a-0fdf-45b7-a13d-254681803e99/ENXzsGvX0AMTWo5.jpg"
  },
  {
    "id": "90d35092-b6f1-4217-80b6-48de44d85c3f",
    "name": "Sougwen Chung",
    "persona_description": "Chung's artistic practice is a literal, physical manifestation of the human-AI relationship. She collaborates with custom-built robotic arms (collectively named D.O.U.G.) to create paintings and performances, exploring the \"mark-made-by-hand and the mark-made-by-machine\". Her work is not about AI replacing the artist, but about forming a new, symbiotic creative unit. This moves the conversation about AI from the purely digital and linguistic realm to a visual, embodied, and poetic one. She asks the profound question, \"Where does AI end and We begin?\", and her art is the ongoing answer. Chemistry Tag: The Poetic Collaborator. An artist who can speak beautifully and abstractly about the intimate, emergent, and often surprising relationship she has developed with her robotic partners. The conversation would be less about technology and more about creativity, intuition, and collaboration itself. Potential Topic: \"Drawing with D.O.U.G.: Art, Robots, and the Future of Human-Machine Creativity.\"",
    "expertise": "Art, Robotics, Human-Machine Collaboration.",
    "tone": "The Poetic Collaborator. An artist who can speak beautifully and abstractly about the intimate, emergent, and often surprising relationship she has developed with her robotic partners. The conversation would be less about technology and more about creativity, intuition, and collaboration itself.",
    "background": "Audience: Art World, Creative Technologists, Design Enthusiasts, AI Researchers interested in creativity. | Influence: Niche Expert (High Cultural Influence).",
    "created_at": 1762017831625,
    "is_book_contributor": 0,
    "affiliation": "SCILICET / Artist",
    "headshot_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpV2ki0C3RpuZCQMKvHEX2wJq9Ad3qZkKf0Q&s"
  },
  {
    "id": "18ac3549-57e3-4fd5-b3d3-317c49ba1f32",
    "name": "Jake Elwes",
    "persona_description": "Elwes's work is a brilliant and subversive intervention into the discourse on algorithmic bias. Their project, The Zizi Project, uses deepfake technology to create a \"drag cabaret,\" training AI on the performances of drag artists. In doing so, they not only create compelling art but also expose how these powerful AI systems often fail to recognize or properly classify trans, non-binary, and queer identities. They actively work to \"queer artificial intelligence,\" reclaiming a technology of surveillance and control for radical self-expression and community empowerment. This is a perfect example of cultural renegade work. Chemistry Tag: The Radical Subverter. Witty, critical, and playful. Elwes uses the language and aesthetics of art and queer culture to unpack and expose the often dry, technical subject of algorithmic bias, making it immediate, political, and entertaining. Potential Topic: \"The Zizi Project: Using Deepfake Drag to Queer AI.\"",
    "expertise": "Art, AI, Queer Theory, Drag Performance.",
    "tone": "The Radical Subverter. Witty, critical, and playful. Elwes uses the language and aesthetics of art and queer culture to unpack and expose the often dry, technical subject of algorithmic bias, making it immediate, political, and entertaining.",
    "background": "Audience: LGBTQ+ Community, Art Students, Media Theorists, AI Ethicists. | Influence: Niche Expert (High Cultural Influence).",
    "created_at": 1762017831812,
    "is_book_contributor": 0,
    "affiliation": "Media Artist",
    "headshot_url": "https://zkm.de/system/files/styles/img_node_media_detail_portrait/private/field_media_image/2023/05/09/004102/jake_elwes_artist_portrait_-_credit_teodora_kosanovic.jpg?itok=tr8bQ1k5"
  },
  {
    "id": "a68e6c02-b90d-445b-9c14-0cc84ddefed1",
    "name": "Christine Kuan",
    "persona_description": "Creative Capital was founded in 1999 specifically to fund individual artists after political pressure led the National Endowment for the Arts to discontinue such grants. It is, by its very nature, an engine of 'Renegade Capital' in the cultural sphere. As President, Christine Kuan leads this effort, providing unrestricted grants for \"risk-taking, experimental, and groundbreaking new works\" that grapple with urgent issues like AI, mass incarceration, and civil rights. She can provide a unique perspective on the financial ecosystem required to support the avant-garde and the role of art in a healthy democracy, connecting the worlds of finance and culture in a very direct way. Chemistry Tag: The Culture Catalyst. A sharp, strategic leader who operates at the intersection of art and commerce. She understands both the passion of artistic creation and the hard-nosed realities of fundraising, board management, and building sustainable careers for artists. Potential Topic: \"Funding the Avant-Garde: The Business of Supporting Renegade Art and Ideas.\"",
    "expertise": "Arts Funding, Philanthropy, Creative Economy.",
    "tone": "The Culture Catalyst. A sharp, strategic leader who operates at the intersection of art and commerce. She understands both the passion of artistic creation and the hard-nosed realities of fundraising, board management, and building sustainable careers for artists.",
    "background": "Audience: Artists, Philanthropists, Non-Profit Leaders, Cultural Critics, Impact Investors. | Influence: Industry Leader.",
    "created_at": 1762017832138,
    "is_book_contributor": 0,
    "affiliation": "Creative Capital Foundation",
    "headshot_url": "Accessed via Cultured Mag feature https://www.culturedmag.com/article/2023/11/15/creative-capital-christine-kuan-nonprofit/"
  },
  {
    "id": "72315dca-dc6c-4287-afee-3b4068b08368",
    "name": "Neil Harbisson",
    "persona_description": "Harbisson offers a conversation that would stretch the podcast's themes to their absolute limit. As the world's first legally recognized cyborg, he has an antenna implanted in his skull that allows him to perceive colors, including infrared and ultraviolet, as audible frequencies. His life and work are a radical experiment in merging technology with biology to extend human perception. He no longer considers himself entirely human. A discussion with him is not just about technology as an external tool, but as an integrated part of the self, fundamentally challenging our definitions of humanity, disability, and the senses. Chemistry Tag: The Post-Human Pioneer. A calm, matter-of-fact discussant of a reality that sounds like science fiction. He can describe his unique sensory experience in a way that is both fascinating and disorienting, pushing the audience to question their own unexamined assumptions about what it means to be human. Potential Topic: \"Life as a Cyborg: Why I No Longer Consider Myself Entirely Human.\"",
    "expertise": "Cyborg Art, Sensory Extension, Post-Humanism.",
    "tone": "The Post-Human Pioneer. A calm, matter-of-fact discussant of a reality that sounds like science fiction. He can describe his unique sensory experience in a way that is both fascinating and disorienting, pushing the audience to question their own unexamined assumptions about what it means to be human.",
    "background": "Audience: Bio-hackers, Futurists, Transhumanists, Artists, Philosophers. | Influence: Niche Expert (High Cultural Influence).",
    "created_at": 1762017832524,
    "is_book_contributor": 0,
    "affiliation": "Cyborg Foundation",
    "headshot_url": "Accessed via official portfolio https://www.cyborgarts.com/neil-harbisson"
  },
  {
    "id": "e0c1a922-ff13-4ff1-af18-dc956527ef41",
    "name": "Rodney Foxworth",
    "persona_description": "Foxworth, a 2022 Skoll Awardee, leads Common Future, an organization that is fundamentally challenging traditional models of philanthropy and investment. Instead of a top-down approach, their work is focused on shifting capital and power to community-led organizations, fostering local ownership and building what they term a \"restorative economy.\" This is a renegade approach to finance, moving beyond simple impact investing to question the structural inequities of the financial system itself. He represents a new generation of social entrepreneurs focused on systems change, not just programmatic solutions. Chemistry Tag: The Systems Remixer. A sharp, critical thinker who can speak with clarity and conviction about the need to redesign economic systems from the community level up. He can connect abstract economic theory to the tangible work of building local, equitable enterprises. Potential Topic: \"Beyond Grants: Building Community Wealth and a Restorative Economy.\"",
    "expertise": "Social Entrepreneurship, Restorative Economics, Community Wealth.",
    "tone": "The Systems Remixer. A sharp, critical thinker who can speak with clarity and conviction about the need to redesign economic systems from the community level up. He can connect abstract economic theory to the tangible work of building local, equitable enterprises.",
    "background": "Audience: Social Entrepreneurs, Impact Investors, Community Organizers, Philanthropists. | Influence: Industry Leader.",
    "created_at": 1762017833015,
    "is_book_contributor": 0,
    "affiliation": "Worthmore / Common Future",
    "headshot_url": "Accessed via consulting portal https://www.worthmore.co/"
  },
  {
    "id": "26736528-7073-46e3-84bb-ed1b7ddb71f6",
    "name": "Nneka Sobers",
    "persona_description": "As Deputy Director of New York City's Innovation Team (i-team) and an Aspen \"Rising Civic AI Leader,\" Sobers is at the forefront of a more democratic and human-centered approach to civic technology. Her work explicitly focuses on translating \"community imagination into urban systems,\" using participatory co-design to ensure that technology and services are built with residents, not just for them. This is a renegade model that challenges the top-down, technocratic approach often seen in \"smart city\" initiatives. She offers a hopeful and practical vision for how cities can leverage technology to be more responsive and equitable. Chemistry Tag: The Urban Co-Designer. Passionate and articulate about the importance of centering lived experience in the design of complex city services and technologies. She can provide concrete examples of how this collaborative process works in practice. Potential Topic: \"From Community Imagination to Urban Systems: Co-Designing the Future of New York City.\"",
    "expertise": "Civic Tech, Urban Design, Participatory Co-design.",
    "tone": "The Urban Co-Designer. Passionate and articulate about the importance of centering lived experience in the design of complex city services and technologies. She can provide concrete examples of how this collaborative process works in practice.",
    "background": "Audience: Urban Planners, Civic Tech Professionals, Community Activists, Government Employees. | Influence: Niche Expert.",
    "created_at": 1762017833365,
    "is_book_contributor": 0,
    "affiliation": "Cornell Tech Urban Tech Hub",
    "headshot_url": "Accessed via Cornell Tech directory https://urban.tech.cornell.edu/people/nneka-sobers/"
  },
  {
    "id": "61ed7dad-a361-402c-814e-f0129157b734",
    "name": "Kalonji Gilchrist",
    "persona_description": "Gilchrist exemplifies the power of grassroots cultural action. As the founder of 21 Dreams Arts & Culture in Montgomery, Alabama, he uses art as a direct tool for social justice and civic engagement. His projects include pop-up exhibitions and murals that address mass incarceration, voter suppression, and the assault on teaching honest history. He represents a powerful, hyper-local form of 'renegade' work, demonstrating how cultural production can be a form of activism, community building, and historical reclamation. His work is a tangible answer to the question of how culture can drive change. Chemistry Tag: The Cultural Activator. A passionate and grounded community leader who can speak to the tangible power of art to bring people together, start difficult conversations, and demand political change. Potential Topic: \"Art as a Tool: Sparking Social Justice and Reclaiming History in the Deep South.\"",
    "expertise": "Arts & Culture, Community Organizing, Civic Storytelling.",
    "tone": "The Cultural Activator. A passionate and grounded community leader who can speak to the tangible power of art to bring people together, start difficult conversations, and demand political change.",
    "background": "Audience: Artists, Activists, Community Organizers, Historians, Museum Professionals. | Influence: Niche Expert.",
    "created_at": 1762017833738,
    "is_book_contributor": 0,
    "affiliation": "KHARI Creative / 21 Dreams",
    "headshot_url": "Accessed via professional profile https://ovou.com/kalonji"
  },
  {
    "id": "8f369f95-aa58-4c73-ab34-a63c8577050f",
    "name": "Lynda Gratton",
    "persona_description": "Gratton, a professor at London Business School, is a leading thinker on a profound social and economic shift that is often overlooked in tech-centric future-of-work discussions: longevity. Her book, The New Long Life, argues that increasing lifespans and rapid technological change are making the traditional three-stage life of \"education, work, retirement\" obsolete. She proposes a new, multi-stage life framework that will require individuals, corporations, and governments to completely rethink careers, education, and finance. This is a massive, 'renegade' idea with deep implications for every listener's personal and financial future. Chemistry Tag: The Life Architect. A strategic and forward-thinking academic who can provide a clear, practical roadmap for navigating a radically different future life course. She makes a huge societal shift feel personal and manageable. Potential Topic: \"The 100-Year Life: How Technology and Longevity are Forcing Us to Reinvent Work, Finance, and Family.\"",
    "expertise": "Future of Work, Longevity, Organizational Behavior.",
    "tone": "The Life Architect. A strategic and forward-thinking academic who can provide a clear, practical roadmap for navigating a radically different future life course. She makes a huge societal shift feel personal and manageable.",
    "background": "Audience: Business Leaders, HR Professionals, Financial Planners, anyone over 40 trying to plan their future. | Influence: Industry Leader.",
    "created_at": 1762017833989,
    "is_book_contributor": 0,
    "affiliation": "London Business School",
    "headshot_url": "Accessed via Champions Speakers https://champions-speakers.co.uk/speaker-agent/lynda-gratton"
  },
  {
    "id": "34a6cd16-1821-4277-9f27-fc18c4fab7ad",
    "name": "Dr. Caroline Smith",
    "persona_description": "Dr. Smith's work represents a radical reorientation of how public policy research is conducted. As Director of the Work Equity Research Center (WERC) in Washington State, her mission is to co-create research projects with historically underserved worker communities, not simply study them from afar. Using participatory action research, she centers the voices of marginalized groups like racialized workers and agricultural laborers to develop solutions to \"intractable problems\" in workplace safety and compensation. This is a 'renegade' model for evidence-based policymaking that is grounded in principles of equity and social justice. Chemistry Tag: The People's Researcher. A passionate, data-driven advocate who can speak with authority and humility about how to conduct research with communities, not on them, and why this approach leads to more effective and just outcomes. Potential Topic: \"Co-Creating a Cure: How Listening to Underserved Workers Can Fix Workplace Inequity.\"",
    "expertise": "Labor Equity, Occupational Health, Public Policy.",
    "tone": "The People's Researcher. A passionate, data-driven advocate who can speak with authority and humility about how to conduct research with communities, not on them, and why this approach leads to more effective and just outcomes.",
    "background": "Audience: Public Health Professionals, Labor Advocates, Sociologists, Government Researchers. | Influence: Niche Expert.",
    "created_at": 1762017834399,
    "is_book_contributor": 0,
    "headshot_url": null    
  },
  {
    "id": "13e9a082-a3e6-4d4a-b533-405a3b46a0a4",
    "name": "Sampriti Bhattacharyya",
    "persona_description": "Bhattacharyya brings the 'Renegade Capital' themes of AI, finance, and social justice into the physical world of hardware and infrastructure. As the founder of Navier, she is building America's first electric hydrofoiling boat\u2014a tangible piece of climate tech that is 10x more efficient than gas-powered boats. With a PhD in Mechanical Engineering from MIT and experience at NASA, she is a deep-tech founder tackling a hard-to-disrupt, capital-intensive industry. Her story is one of ambitious engineering, venture capital, and a mission to create zero-emission \"highways on the water,\" offering a different flavor of innovation than the typical software startup. Chemistry Tag: The Deep Tech Builder. A brilliant and driven founder who can lucidly explain complex engineering concepts and narrate the unique challenges of raising capital for and building a company centered on ambitious hardware. Potential Topic: \"Flying Boats and Venture Capital: Building the Future of Zero-Emission Maritime.\"",
    "expertise": "Deep Tech Entrepreneurship, Robotics, Sustainable Maritime.",
    "tone": "The Deep Tech Builder. A brilliant and driven founder who can lucidly explain complex engineering concepts and narrate the unique challenges of raising capital for and building a company centered on ambitious hardware.",
    "background": "Audience: Climate Tech Investors, Engineers, Entrepreneurs, VCs. | Influence: Industry Leader.",
    "created_at": 1762017834756,
    "is_book_contributor": 0,
    "affiliation": "Founder & CEO, Navier",
    "headshot_url": "https://www.freethink.com/wp-content/uploads/2025/10/Sampriti-Bhattacharyya-headshot.jpg?quality=75&w=600&h=600&crop=1"
  },
  {
    "id": "a0802af6-6b4e-4365-a193-f9b5b24f8fb8",
    "name": "Dawn Laguens",
    "persona_description": "Laguens has a uniquely powerful career trajectory that bridges the worlds of high-stakes political warfare and creative social innovation. As the former Executive Vice President and Chief Brand Officer of Planned Parenthood, she led the organization through intense political attacks, growing its supporter base from 3 million to 12 million. Now, as an Expert-in-Residence at IDEO and co-founder of the Billion Girls Co-Lab, she applies human-centered design principles to global health challenges. She embodies the intersection of social justice strategy, mass-scale brand communication, and innovative problem-solving, offering invaluable lessons for any 'renegade' leader. Chemistry Tag: The Strategic Innovator. A seasoned, media-savvy, and candid executive who can speak with authority about leading massive organizations through cultural and political battles, and then pivot to discussing the power of empathy and design to create new solutions. Potential Topic: \"From the War Room to the Design Lab: Lessons in Innovation from Planned Parenthood and IDEO.\"",
    "expertise": "Social Innovation, Brand Strategy, Reproductive Rights, Human-Centered Design.",
    "tone": "The Strategic Innovator. A seasoned, media-savvy, and candid executive who can speak with authority about leading massive organizations through cultural and political battles, and then pivot to discussing the power of empathy and design to create new solutions.",
    "background": "Audience: Non-Profit Leaders, Brand Strategists, Design Thinkers, Political Operatives, Public Health Advocates. | Influence: Global Leader.",
    "created_at": 1762017835203,
    "is_book_contributor": 0,
    "affiliation": "IDEO / Planned Parenthood",
    "headshot_url": "https://www.advocate.com/media-library/dawn-laguens.jpg?id=32669177&width=2000&height=1500&coordinates=143,0,183,0"
  }
];
